language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk11
env: NODE_VERSION=10.2.1
before_install: nvm install $NODE_VERSION
script:
  - ./gradlew :shared:test -i
  - ./gradlew :server:test -i

jobs:
  include:
    - stage: "Deploy"
      before_deploy:
        - ./gradlew :server:distZip
        - ./gradlew :grammars:distZip
      deploy:
        provider: releases
        api_key: $API_KEY
        file_glob: true
        file:
          - "server/build/distributions/*.zip"
          - "grammars/build/distributions/*.zip"
        skip_cleanup: true
        name: "Version $TRAVIS_TAG"

